<?php
bolt_decrypt( __FILE__ , 'AbS1cr'); return 0;
##!!!##CQYJBmpdaWFvbF1fYRw9bGxYSWtgYWhvNwkGCQZxb2EcRWhocWllal1wYVhAXXBdXl1vYVhBaGttcWFqcFhCXV9wa25lYW9YRF1vQl1fcGtudTcJBnFvYRxFaGhxaWVqXXBhWEBdcF1eXW9hWEFoa21xYWpwWElrYGFoNwkGCQZfaF1vbxxJXWVqUHVsYRxhdHBhamBvHElrYGFoCQZ3CQYcHBwccW9hHERdb0JdX3BrbnU3CQZ5CQY=